### ISSUE TITLE
新路由3编译被取消

### ISSUE THREAD

**Issue by Thanf-code** [Hyy2001X/AutoBuild-Actions#101]
![Screenshot_20210829_181659](https://user-images.githubusercontent.com/82493550/131271062-30255d02-8094-4701-bc11-b5871617ce5a.jpg)
设备架构mips  mt7621  d-team_newifi-d2
默认编译能通过，登录ssh选择插件后编译就不行了

**Comment by Hyy2001X** [comment]
这个问题我也没遇到过，不是很清楚🤣

**Comment by Thanf-code** [comment]
> 这个问题我也没遇到过，不是很清楚🤣

是github取消编译了
