### ISSUE TITLE
请问.config文件是指哪里的？

### ISSUE THREAD

**Issue by ba1dh3ad** [Hyy2001X/AutoBuild-Actions#106]
指南中提到 “文中的TARGET_PROFILE为设备名称,可以在.config中获取,例如: d-team_newifi-d2” ，请问.config在哪里呢？

**Comment by Hyy2001X** [comment]
在本地的`lede`源码目录下,执行`make menuconfig`后自动生成
![file](https://user-images.githubusercontent.com/25874819/133353053-c261e9f0-02ea-4c51-835c-203a250edd56.png)

**Comment by ba1dh3ad** [comment]
十分感谢
