### ISSUE TITLE
[BUG]新版本AutoUpdate获取固件版本时会截断版本号

### ISSUE THREAD

**Issue by Ai-desu-2333** [Hyy2001X/AutoBuild-Actions#113]
如题，当使用AutoBuild编译固件时如果关闭了简短固件日期选项，
即  _AutoBuild_DiyScript.sh_ 中 `Short_Firmware_Date=false` 时，固件名会从 **年月日** 变为 **年月日时分** 
新版本AutoUpdate获取固件版本号不会获取至 固件名的 **时分**，仅会获取 **年月日**

![image](https://user-images.githubusercontent.com/61218958/139591267-a4ecfb3f-cf99-40e3-ba52-d59ba51dba62.png)

![image](https://user-images.githubusercontent.com/61218958/139591274-e1660629-b9b2-44e6-abc7-6dfdc269b586.png)

**Comment by Hyy2001X** [comment]
感谢反馈，我抽空修复一下

**Comment by Ai-desu-2333** [comment]
新版本解决了，Nice！
