### ISSUE TITLE
NEWIFI-D2 wan 限制在100M

### ISSUE THREAD

**Issue by sinoyster** [Hyy2001X/AutoBuild-Actions#122]
你好，感谢您制作的固件，很好用！
我是NEWIFI3-D2用户，使用11月16日的固件，发现WAN口只有100M的速度。切换为padavan就能恢复到1000M，排除网线和上级路由的问题。麻烦大佬了看看

**Comment by Hyy2001X** [comment]
收到，感谢反馈

**Comment by Hyy2001X** [comment]
测试了1122版本固件，测速尚未发现该问题
你遇到的这个问题可能是上游更新 ppp 导致的，等更新吧

**Comment by sinoyster** [comment]
1122版本无问题，完美使用，谢谢大佬
