### ISSUE TITLE
建议使用Maximize build space 增加编译空间

### ISSUE THREAD

**Issue by kokeri** [Hyy2001X/AutoBuild-Actions#125]
示例如下：
`  - name: Maximize build space`
`      uses: easimon/maximize-build-space@master`
`      with:`
`        root-reserve-mb: 10240`
`        swap-size-mb: 1`
`        remove-dotnet: 'true'`
`        remove-android: 'true'`
使用后硬盘可用空间大致在50G

**Comment by Hyy2001X** [comment]
非常感谢你的建议，方便好用😁
