### ISSUE TITLE
请问能否添加passwall插件

### ISSUE THREAD

**Issue by qqqiuuu** [Hyy2001X/AutoBuild-Actions#126]
你好，我是小娱c5用户，更新了12月7日的固件之后，发现clash插件似乎被删了。请问能否添加个passwall代替一下openclash呢？

**Comment by NaiHeKK** [comment]
AutoBuild_DiyScript.sh中添加 `AddPackage git other openwrt-passwall xiaorouji main`
Config中添加 `CONFIG_PACKAGE_luci-app-passwall=y`

**Comment by qqqiuuu** [comment]
谢谢
