### ISSUE TITLE
关于删除包的问题

### ISSUE THREAD

**Issue by qqqiuuu** [Hyy2001X/AutoBuild-Actions#127]
你好大神。我编译前把config的luci-app-accesscontrol（应该是上网时间控制）引用掉了，可是编译的时候还是会添加这个包。还有就是我没有取消argon主题的包，编译的固件却没有这个主题，进入后台软件包只显示安装了主题的luciapp，请问大佬有遇到过这种情况吗？我搞了一晚上还是不太行

**Comment by Hyy2001X** [comment]
不要的包改成 # xxx is not set 就好了，不要直接删掉
没有主题不保留配置刷入试试

**Comment by qqqiuuu** [comment]
> 不要的包改成 # xxx is not set 就好了，不要直接删掉 没有主题不保留配置刷入试试

牛！改成is not set 有效。主题问题目前还在找原因，我在breed刷入和在luci不保留配置刷入都试过了，我再看看我的config有没有什么毛病，十分感谢大佬解答小白的疑惑
