### ISSUE TITLE
无法自动升级

### ISSUE THREAD

**Issue by RogerHuHu** [Hyy2001X/AutoBuild-Actions#130]
root@NEWIFI3:/bin# ./AutoUpdate.sh --verbose

[01:27:32] 未检测到环境变量: OP_VERSION

[01:27:32] 未检测到环境变量: OP_AUTHOR

[01:27:32] 未检测到环境变量: OP_REPO
Openwrt-AutoUpdate Script by Hyy2001 V6.8.2

[01:27:32] 特殊指令: [详细信息] | /sbin/sysupgrade -q

[01:27:32] 执行: 更新固件

[01:27:35] 正在检查固件版本更新 ...
--2021-12-22 01:27:36--  https://ghproxy.com/https://github.com/Hyy2001X/AutoBuild-Actions/releases/download/AutoUpdate/API
Resolving ghproxy.com... 132.226.238.71
Connecting to ghproxy.com|132.226.238.71|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 25241 (25K) [application/octet-stream]
Saving to: '/tmp/AutoUpdate/API_Cache'

/tmp/AutoUpdate/API_Cache                                                                  100%[======================================================================================================================================================================================================================================>]  24.65K  --.-KB/s    in 0.003s

2021-12-22 01:27:40 (8.37 MB/s) - '/tmp/AutoUpdate/API_Cache' saved [25241/25241]

[01:27:41] Github API 解析内容为空!

**Comment by Hyy2001X** [comment]
应该是固件版本比较老，手动更新一下就好了
