### ISSUE TITLE
11.11版本ssr无法开启

### ISSUE THREAD

**Issue by 1812z** [Hyy2001X/AutoBuild-Actions#14]
开启秒关闭，日志无有用内容[只有start和end]
[已经全新安装]
d2

**Comment by niceran** [comment]
没有集成ss和ssr核心，这两个东西都过时，被墙认别了。建议使用v2ray和torxxx。。。。

**Comment by 1812z** [comment]
> 没有集成ss和ssr核心，这两个东西都过时，被墙认别了。建议使用v2ray和torxxx。。。。

是自动的固件问题，，，我用的vless
