### ISSUE TITLE
新3无法扩展USB空间

### ISSUE THREAD

**Issue by lbcz-tian** [Hyy2001X/AutoBuild-Actions#145]
用最新的0206版本，无法配置USB空间扩展😢😢，麻烦大佬看看是咋回事呀
![image](https://user-images.githubusercontent.com/62131027/156690237-1b02c624-2384-4b39-95d6-d7a358b2eecf.png)

**Comment by acgbox233** [comment]
我的也是这个毛病。

**Comment by lbcz-tian** [comment]
试了一圈，我这用2211215版本可以正常扩展空间，暂时不升级了😢

**Comment by acgbox233** [comment]
> 试了一圈，我这用20211215版本可以正常扩展空间，暂时不升级了😢
我找不到旧版本了，作者这边把旧版本删了。

**Comment by acgbox233** [comment]
> 试了一圈，我这用20211215版本可以正常扩展空间，暂时不升级了😢

我找不到旧版本了，作者这边把旧版本删了。

**Comment by lbcz-tian** [comment]
> > 试了一圈，我这用20211215版本可以正常扩展空间，暂时不升级了😢
> 
> 我找不到旧版本了，作者这边把旧版本删了。 目前我换成了H大的老毛子padavan了。

padavan咋样，我没用过额
旧版在恩山论坛里有，提取码tw2s
https://pan.baidu.com/s/1T69H1nZ_y8RqMhc80nV8LQ

**Comment by NaiHeKK** [comment]
我都是通过挂载点挂载到overlay的，就是每次升级完需要格一次U盘

**Comment by acgbox233** [comment]
> > > 试了一圈，我这用20211215版本可以正常扩展空间，暂时不升级了😢
> > 
> > 
> > 我找不到旧版本了，作者这边把旧版本删了。 目前我换成了H大的老毛子padavan了。
> 
> padavan咋样，我没用过额 旧版在恩山论坛里有，提取码tw2s https://pan.baidu.com/s/1T69H1nZ_y8RqMhc80nV8LQ

最新编译的openwrt固件在我这台新路由3上容易卡死重启，插上U盘的一瞬间也会卡死并重启，以前的版本从没出现过这种现象。我还一度以为是路由器本身老化了或者硬件出故障了。而换回到padavan后则稳定了很多，WiFi质量也更好。目前看来没有遇到卡死又重启的现象。

附上padavan官方下载地址：[https://opt.cn2qq.com/padavan/](https://opt.cn2qq.com/padavan/)

**Comment by lbcz-tian** [comment]
> > > > 试了一圈，我这用20211215版本可以正常扩展空间，暂时不升级了😢
> > > 
> > > 
> > > 我找不到旧版本了，作者这边把旧版本删了。 目前我换成了H大的老毛子padavan了。
> > 
> > 
> > padavan咋样，我没用过额 旧版在恩山论坛里有，提取码tw2s https://pan.baidu.com/s/1T69H1nZ_y8RqMhc80nV8LQ
> 
> 最新编译的openwrt固件在我这台新路由3上容易卡死重启，插上U盘的一瞬间也会卡死并重启，以前的版本从没出现过这种现象。我还一度以为是路由器本身老化了或者硬件出故障了。而换回到padavan后则稳定了很多，WiFi质量也更好。目前看来没有遇到卡死又重启的现象。
> 
> 附上padavan官方下载地址：https://opt.cn2qq.com/padavan/

感谢老哥🤗
我自己fork后编译的固件，也是会不定时重启，用了4天重启了5次，我先看看旧版本会不会有这个问题😂，如果还这样我就刷padavan看看

**Comment by lbcz-tian** [comment]
> 我都是通过挂载点挂载到overlay的，就是每次升级完需要格一次U盘

我搜搜教程，还不太会整🤣

**Comment by acgbox233** [comment]
> > 我都是通过挂载点挂载到overlay的，就是每次升级完需要格一次U盘
> 
> 我搜搜教程，还不太会整🤣

我之前不知道这个固件有自动挂载功能，一直都是手动挂载的，参考的是这个教程：[https://iyzm.net/openwrt/92.html](https://iyzm.net/openwrt/92.html)，实测可行。

**Comment by Hyy2001X** [comment]
> 用最新的0206版本，无法配置USB空间扩展😢😢，麻烦大佬看看是咋回事呀 ![image](https://user-images.githubusercontent.com/62131027/156690237-1b02c624-2384-4b39-95d6-d7a358b2eecf.png)

感谢反馈，下个版本修复

**Comment by Hyy2001X** [comment]
> 我的也是这个毛病。

感谢反馈，下个版本修复

**Comment by lbcz-tian** [comment]
> > 用最新的0206版本，无法配置USB空间扩展😢😢，麻烦大佬看看是咋回事呀 ![image](https://user-images.githubusercontent.com/62131027/156690237-1b02c624-2384-4b39-95d6-d7a358b2eecf.png)
> 
> 感谢反馈，下个版本修复

哇大佬要恢复更新了吗，期待一波😋😋

**Comment by lbcz-tian** [comment]
新版0313已可扩展空间，感谢大佬们。
我之前用1215旧版会经常性重启，不知道啥原因，个人使用会挂PT，大约5000种，查看连接数大约在6000-9000波动。先换0313版看看会不会有重启，再次感谢大佬们😋😋
