### ISSUE TITLE
固件很好用，但是有一个bug，接口页面下每个接口的流量统计都不准确

### ISSUE THREAD

**Issue by wongchiching** [Hyy2001X/AutoBuild-Actions#150]
目前功能最全最好用的新路由3固件。
但是有一个bug，【接口】页面下每个接口的发送和接收的流量统计都不准确。
不知道是不是我个人设定的问题？

**Comment by Hyy2001X** [comment]
关闭硬件NAT加速试试

**Comment by wongchiching** [comment]
> 关闭硬件NAT加速试试

请问在哪里关闭 @Hyy2001X

**Comment by wongchiching** [comment]
> 关闭硬件NAT加速试试

谢谢大神， 已经找到地方关闭，关掉后流量统计正常了，好奇问下，关掉这个后会有什么影响吗？

**Comment by Hyy2001X** [comment]
> > 关闭硬件NAT加速试试
> 
> 谢谢大神， 已经找到地方关闭，关掉后流量统计正常了，好奇问下，关掉这个后会有什么影响吗？

关掉以后网络性能会降低很多，不建议关闭
