### ISSUE TITLE
这个支持openvpn吗？

### ISSUE THREAD

**Issue by triumph** [Hyy2001X/AutoBuild-Actions#151]
各位大神辛苦了。感谢为我们编译出这么好的固件。
这个支持openvpn吗？我看配置文件，好像没有 openvpn，大神能说下吗？。谢谢。

**Comment by Hyy2001X** [comment]
需要自己编译，编译的时候在 config 里加上 luci-app-openvpn

**Comment by impl1874** [comment]
加了luci-app-openvpn可以安装成功，但是命令行没有openvpn命令，lede的packages里有[openvpn](https://github.com/coolsnowwolf/packages/tree/master/net/openvpn)或者叫openvpn-openssl，添加或者不添加这一行是没有作用的[x86_64:118](https://github.com/impl1874/AutoBuild-Actions-Template/blob/master/Configs/x86_64)

下载Actions的编译[日志](https://github.com/impl1874/AutoBuild-Actions-Template/runs/5860105910?check_suite_focus=true)只有luci-app-openvpn compile，而没有openvpn compile、openvpn-openssl compile
