### ISSUE TITLE
0323版本无法自动挂载NTFS格式的U盘

### ISSUE THREAD

**Issue by 383771059** [Hyy2001X/AutoBuild-Actions#154]
0323版本无法自动挂载NTFS格式的U盘，请fix bug，我现在的共享都用不了了。

**Comment by acgbox233** [comment]
我用DiskGenius软件删除U盘分区并格式化为FAT32，就可以自动挂载了。用win10自带的格式化后无法自动挂载。

**Comment by Hyy2001X** [comment]
试试最新版的固件能不能自动挂载上
