### ISSUE TITLE
这个如何添加自己要增加的源码仓库

### ISSUE THREAD

**Issue by luchen7** [Hyy2001X/AutoBuild-Actions#155]
这个如何添加自己要增加的源码仓库

**Comment by Hyy2001X** [comment]
编辑 Scripts/AutoBuild_DiyScript.sh
如果要添加 passwall，就在23行到87之间加上这两行
AddPackage git passwall-depends openwrt-passwall xiaorouji packages
AddPackage git passwall-luci openwrt-passwall xiaorouji luci

**Comment by luchen7** [comment]
NEWIFI D2 / Compile 
Failed in 5 minutes and 49 seconds
![Uploading 76D46ED3-4CFF-46E7-A92B-BCD17A6B4274.png…]()

**Comment by luchen7** [comment]
![image](https://user-images.githubusercontent.com/10656546/161410882-33e92b25-6236-4aa5-b1d9-c7ae158016ad.png)

**Comment by luchen7** [comment]
编译时候报错

**Comment by Hyy2001X** [comment]
> 编译时候报错

位置加错了, 加到 esac 的下一行

**Comment by luchen7** [comment]
我图片上的89和90中间吗

**Comment by luchen7** [comment]
还是81和82中间

**Comment by Hyy2001X** [comment]
> 我图片上的89和90中间吗

是的

**Comment by luchen7** [comment]
好的 对了  passwall  xiaorouji好像弄成什么passwall2了  跟这个没关系拔

**Comment by Hyy2001X** [comment]
> 好的 对了 passwall xiaorouji好像弄成什么passwall2了 跟这个没关系拔

openwrt-passwall2 仓库要这么写,有点区别: `AddPackage git passwall-luci openwrt-passwall2 xiaorouji main`

**Comment by luchen7** [comment]
那刚才的两条还要增加吗  还是只增加这一条

**Comment by luchen7** [comment]
给个建议啊  能否直接给passwall增加进去  多一个选择  你的这个固件太好用了  适合新手  我现在有16台设备再用你的固件  主要我需要PASSWALL的按端口分流

**Comment by luchen7** [comment]
![image](https://user-images.githubusercontent.com/10656546/161411808-fee31fd5-b972-4602-be4f-44c50e44b93c.png)
还是编译错误

**Comment by Hyy2001X** [comment]
> 

你按照我的最新提交修改一下那一行

**Comment by luchen7** [comment]
你最新提交的是不是已经带PASSWALL了？

**Comment by luchen7** [comment]
可以加下TG吗？https://t.me/xygggggg
