### ISSUE TITLE
大佬新人有疑问

### ISSUE THREAD

**Issue by yxnoicq** [Hyy2001X/AutoBuild-Actions#159]
新关注没找着刷机底包，用别的底包刷砖啊。求告知用什么底包。谢谢大佬。新关注见量。

**Comment by Hyy2001X** [comment]
啥型号的机器呀

**Comment by yxnoicq** [comment]
> 啥型号的机器呀
AX6S呀大佬

**Comment by Hyy2001X** [comment]
> > 啥型号的机器呀
> > AX6S呀大佬

理论上别人的底包也能用吧 我一开始就是刷的别人的底包上来的
