### ISSUE TITLE
哦能提供下下吗，没有的话只能恩山AX6S区全试一遍了，官方原生底包你说行不行呢？> > 啥型号的机器呀

### ISSUE THREAD

**Issue by yxnoicq** [Hyy2001X/AutoBuild-Actions#160]
> > 啥型号的机器呀
> > AX6S呀大佬

理论上别人的底包也能用吧 我一开始就是刷的别人的底包上来的

_Originally posted by @Hyy2001X in https://github.com/Hyy2001X/AutoBuild-Actions/issues/159#issuecomment-1100558116_

**Comment by Hyy2001X** [comment]
试试这个 https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/mediatek/mt7622/immortalwrt-mediatek-mt7622-xiaomi_redmi-router-ax6s-squashfs-factory.bin

**Comment by yxnoicq** [comment]
谢谢
