### ISSUE TITLE
可以增加钉钉提供的内网穿透工具吗？

### ISSUE THREAD

**Issue by cdphantom** [Hyy2001X/AutoBuild-Actions#163]
钉钉提供的内网穿透工具
https://github.com/open-dingtalk/pierced.git

[钉钉开放平台](https://www.dingtalk.com/qidian/help-category-218.html) — 内网穿透
关于内网穿透之HTTP穿透的详细介绍，请点击链接查看：https://developers.dingtalk.com/document/resourcedownload/http-intranet-penetration?pnamespace=app

**Comment by Hyy2001X** [comment]
openwrt 好像运行不了官网提供的二进制文件
