### ISSUE TITLE
AX6S

### ISSUE THREAD

**Issue by sss132919** [Hyy2001X/AutoBuild-Actions#172]
大佬你好，我看到这边编译版本有ax6s的固件，但是我使用恩山论坛的，刷入底包后，无配置刷入，机器会变成黄灯亮一会儿就灭，无法刷入使用，请问一下，这个ax6s的固件是有特定的刷入方法吗？还是此固件并不是面向所有人的？
如果有解法方法，可否提点一下？

**Comment by Hyy2001X** [comment]
不好意思，试试刷一下这里的 factory 底包看看能不能开机
https://downloads.immortalwrt.org/releases/18.06-k5.4-SNAPSHOT/targets/mediatek/mt7622/

**Comment by sss132919** [comment]
刷了提供的底包，可以正常刷入使用了😁

**Comment by sss132919** [comment]
大佬你好，好像会有偶尔重启的现象
