### ISSUE TITLE
J4125物理机无法启动

### ISSUE THREAD

**Issue by buggy-go** [Hyy2001X/AutoBuild-Actions#176]
uefi和bios均无法启动，启动时长期停在左上角光标闪烁界面。但PVE虚拟机可以启动，不知道哪个版本开始的。

**Comment by buggy-go** [comment]
另，固件虽然能编译出来，但编译任务显示失败。

**Comment by Hyy2001X** [comment]
> 另，固件虽然能编译出来，但编译任务显示失败。

显示任务失败无大碍，是最后清理旧 Actions 那部分错误了不影响编译和出包

**Comment by Hyy2001X** [comment]
> uefi和bios均无法启动，启动时长期停在左上角光标闪烁界面。但PVE虚拟机可以启动，不知道哪个版本开始的。

[这行](https://github.com/Hyy2001X/AutoBuild-Actions/blob/37f6dc539ad05039d897ecdaebd579a27c646017/Configs/x86_64#L10)删掉试试再编译，我这边物理机虚拟机都正常 5105

**Comment by buggy-go** [comment]
> 

感谢，我试一下

**Comment by buggy-go** [comment]
> 

删除这行后解决，另外更正以下，我的电脑是J4105。
