### ISSUE TITLE
自己编译的固件固件更新检测不到环境变量

### ISSUE THREAD

**Issue by Paris0-0** [Hyy2001X/AutoBuild-Actions#178]
用您编译好的是可以正常检测到更新的，自己编译的提示
[36m[08:53:48][0m[31m 警告: 未检测到环境变量: [TARGET_FLAG][0mhttps://github.com/Paris0-0/AutoBuild-Actions

**Comment by lgfyxx** [comment]
我是之前正常，最近几天更新的固件也变成这样了，同求解决办法。 并且打开固件更新选项加载巨慢， tools 修复环境无效。

**Comment by Hyy2001X** [comment]
> 用您编译好的是可以正常检测到更新的，自己编译的提示 [36m[08:53:48][0m[31m 警告: 未检测到环境变量: [TARGET_FLAG][0mhttps://github.com/Paris0-0/AutoBuild-Actions

AutoBuild_DiyScript.sh 这个文件也同步一下改动，变量名称有一些改动

**Comment by Paris0-0** [comment]
同步了下，x86编译超时，好像是docker占的时间太长了
