### ISSUE TITLE
求助!!!大佬你好,我的路由每天都会断网很多次,每次的日志大体都是这样的,烦请帮忙给看看咋回事?

### ISSUE THREAD

**Issue by Waradise** [Hyy2001X/AutoBuild-Actions#179]
Thu Jun  2 21:25:51 2022 daemon.notice procd: /etc/rc.d/S99zerotier: disabled in config
Thu Jun  2 21:25:51 2022 daemon.info procd: - init complete -
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]: ttyd 1.6.3 (libwebsockets 4.1.6-20211107-630-g5dba0b8be)
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]: tty configuration:
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]:   start command: /usr/libexec/login.sh
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]:   close signal: SIGHUP (1)
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]:   terminal type: xterm-256color
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]: LWS: 4.1.6-20211107-630-g5dba0b8be, loglevel 7
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]: NET CLI SRV H1 H2 WS IPV6-off
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]:    /usr/lib/libwebsockets-evlib_uv.so
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]:  Using foreign event loop...
Thu Jun  2 21:25:52 2022 daemon.notice ttyd[6311]:  Listening on port: 7681
Thu Jun  2 21:26:25 2022 cron.err crond[6026]: time disparity of 807 minutes detected

**Comment by Hyy2001X** [comment]
好像没看出问题
