### ISSUE TITLE
x86编译超时

### ISSUE THREAD

**Issue by Paris0-0** [Hyy2001X/AutoBuild-Actions#180]
自己fork的和您的都超时了

**Comment by Hyy2001X** [comment]
精简些软件包看看

**Comment by Paris0-0** [comment]
看了下我们两个的日志,中间软件包编译都是三个多小时,到最后make[3] -C package/lean/default-settings compile就卡住了,前两天都编译成功了软件包我还删了几个,就是lean大最新修复以后编译不成功的[https://github.com/coolsnowwolf/lede/commit/2a33e979c850c9bf214e6713a9e39ada029e2381](url)

**Comment by Paris0-0** [comment]
> 精简些软件包看看

精简了些,还是一样,跑满6h超时,感觉是卡死了

**Comment by Paris0-0** [comment]
删了好些个包终于卡着6h编译完了..怎么突然这么慢
