### ISSUE TITLE
是否可以在编译前加入github actions cache缓存来达到二次编译加速的效果？

### ISSUE THREAD

**Issue by e5u** [Hyy2001X/AutoBuild-Actions#196]
https://github.com/coolsnowwolf/lede/pull/7796

我看到 281677160 的仓库加入了缓存，的确可以达到加速编译的效果
https://github.com/281677160/build-actions/blob/main/.github/workflows/compile.yml#L83

**Comment by Hyy2001X** [comment]
感谢老哥的建议， 已经添加了
