### ISSUE TITLE
newifi d2 clash版死机

### ISSUE THREAD

**Issue by Shad0w1and** [Hyy2001X/AutoBuild-Actions#201]
版本为R22.8.2-20220806
新三开启openclash后使用浏览器SwitchyOmega连接socks5代理，会直接造成死机。此外似乎udp加速无法生效。烦大佬有空修复，现在不敢用clash代理了。

**Comment by Hyy2001X** [comment]
这个要反馈到 OpenClash 的[官方](https://github.com/vernesong/OpenClash/issues)，我处理不了，反馈的时候最好加一下日志
