### ISSUE TITLE
升级后掉主题

### ISSUE THREAD

**Issue by MasterOfStar** [Hyy2001X/AutoBuild-Actions#203]
newifi3d2 R22.5.5 [2022/06/02] 通过6.9.3脚本在ttyd中autoupdate至R22.8.2 [2022/08/06]
升级完成后自带的argon主题未生效
进入breed重刷，主题仍未生效

目前已回滚至R22.5.5

**Comment by Hyy2001X** [comment]
下一版会修复的，感谢反馈
