### ISSUE TITLE
编译竞斗云固件报错

### ISSUE THREAD

**Issue by Gangnamsstyle** [Hyy2001X/AutoBuild-Actions#207]
/home/runner/work/_temp/736f536e-fd66-4df7-90b2-30418e5f9082.sh: line 11: Firmware_Diy_Before: command not found
Error: Process completed with exit code 127.

**Comment by Hyy2001X** [comment]
看了一下你 fork 的仓库，代码都太老啦，同步更新一下最新的吧

**Comment by Gangnamsstyle** [comment]
> 看了一下你 fork 的仓库，代码都太老啦，同步更新一下最新的吧

![image](https://user-images.githubusercontent.com/69400033/188777299-7c054a72-bbfe-497f-8282-de7e09122312.png)
你好，更新同步后可以完成编译了，但是编译完成后，怎么没法下载固件呢？

**Comment by Hyy2001X** [comment]
> 

编译好的[在这里](https://github.com/Gangnamsstyle/AutoBuild-Actions/releases/tag/AutoUpdate)
