### ISSUE TITLE
base not found

### ISSUE THREAD

**Issue by NaiHeKK** [Hyy2001X/AutoBuild-Actions#22]
你好，我fork您的仓库后改了配置把zerotier和openclash注掉、V2ray改成了Xray，编译后的版本无法自动更新，终端执行更新命令提示“**bash not found**“。
  请问是什么情况啊？哪个不能注掉吗

**Comment by Hyy2001X** [comment]
尝试在 .config 中添加一行 CONFIG_PACKAGE_bash=y

**Comment by NaiHeKK** [comment]
非常感谢，我去试试看

**Comment by NaiHeKK** [comment]
> 尝试在 .config 中添加一行 CONFIG_PACKAGE_bash=y


解决了，非常感谢
