### ISSUE TITLE
2021-1-10日后fork的库不能自动编译了。。

### ISSUE THREAD

**Issue by konbar** [Hyy2001X/AutoBuild-Actions#26]
2021-1-10日后fork的库不能自动编译了。。反复几次按说明修改都不能自动编译，谢谢H大大的库
![2021-01-16 160844](https://user-images.githubusercontent.com/22516445/104806813-2e57de00-5815-11eb-9e93-f70fbab5e0e9.png)

**Comment by Hyy2001X** [comment]
不好意思，这个情况我也不是很清楚

**Comment by NaiHeKK** [comment]
重新fork吧，之后的更新用pr来更新
