### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by NaiHeKK** [Hyy2001X/AutoBuild-Actions#31]
在Diy-Part1时编译失败，我的库和你的库都失败了
smartdns库不存在了

**Comment by Hyy2001X** [comment]
smartdns指向的CTCGFW团队维护的仓库因为某些原因暂时删库了。。我会更换新的仓库链接

**Comment by NaiHeKK** [comment]
> smartdns指向的CTCGFW团队维护的仓库因为某些原因暂时删库了。。我会更换新的仓库链接

妈耶，去看了下，这个nobk是谁

**Comment by Hyy2001X** [comment]
已经修复地址可以正常编译了

**Comment by NaiHeKK** [comment]
> 已经修复地址可以正常编译了

好的，谢谢
