### ISSUE TITLE
是否可以集成transmission啊

### ISSUE THREAD

**Issue by caoyipeng2008** [Hyy2001X/AutoBuild-Actions#32]

**Comment by Hyy2001X** [comment]
可以自己fork我的仓库进行编译，config里加上CONFIG_PACKAGE_luci-app-transmission=y,再删掉你不需要的软件包就好了

**Comment by NaiHeKK** [comment]
> 可以自己fork我的仓库进行编译，config里加上CONFIG_PACKAGE_luci-app-transmission=y,再删掉你不需要的软件包就好了

将AutoBuild_DiyScript.sh的passwall改成true后，是不是也要在config里加上CONFIG_PACKAGE_luci-app-passwall=y啊？

**Comment by Hyy2001X** [comment]
对

**Comment by NaiHeKK** [comment]
> 对

好的，谢谢了

**Comment by caoyipeng2008** [comment]
> 可以自己fork我的仓库进行编译，config里加上CONFIG_PACKAGE_luci-app-transmission=y,再删掉你不需要的软件包就好了

谢谢，请问一下这些配置项说明在哪里可以找到？

**Comment by Hyy2001X** [comment]
> > 可以自己fork我的仓库进行编译，config里加上CONFIG_PACKAGE_luci-app-transmission=y,再删掉你不需要的软件包就好了
> 
> 谢谢，请问一下这些配置项说明在哪里可以找到？

大多需要自己摸索，luci-app说明参见esir大神的https://drive.google.com/drive/mobile/folders/1dqNUrMf9n7i3y1aSh68U5Yf44WQ3KCuh
