### ISSUE TITLE
能不能增加内网穿透NPS服务端的插件

### ISSUE THREAD

**Issue by sirliu** [Hyy2001X/AutoBuild-Actions#33]
能不能增加内网穿透NPS服务端的插件
NPS内网穿透项目在此https://github.com/ehang-io/nps
本人已通过项目编译好的压缩包安装并可以成功运行。唯一不足是不能开机自启动。

**Comment by NaiHeKK** [comment]
luci-app-nps我发现package里有个这个包

**Comment by sirliu** [comment]
> luci-app-nps

你的源能分享下嘛，我的是这样的源，里面没有发现，设备是newifi3 d2：
`src/gz openwrt_core https://mirrors.cloud.tencent.com/lede/snapshots/targets/ramips/mt7621/packages
src/gz openwrt_base https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/base
src/gz openwrt_freifunk https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/freifunk
src/gz openwrt_luci https://mirrors.cloud.tencent.com/lede/releases/18.06.8/packages/mipsel_24kc/luci
src/gz openwrt_packages https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/packages
src/gz openwrt_routing https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/routing
src/gz openwrt_telephony https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/telephony`

**Comment by NaiHeKK** [comment]
> > luci-app-nps
> 
> 你的源能分享下嘛，我的是这样的源，里面没有发现，设备是newifi3 d2：
> `src/gz openwrt_core https://mirrors.cloud.tencent.com/lede/snapshots/targets/ramips/mt7621/packages src/gz openwrt_base https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/base src/gz openwrt_freifunk https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/freifunk src/gz openwrt_luci https://mirrors.cloud.tencent.com/lede/releases/18.06.8/packages/mipsel_24kc/luci src/gz openwrt_packages https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/packages src/gz openwrt_routing https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/routing src/gz openwrt_telephony https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/telephony`

直接在config里添加就行应该

**Comment by sirliu** [comment]
> > > luci-app-nps
> > 
> > 
> > 你的源能分享下嘛，我的是这样的源，里面没有发现，设备是newifi3 d2：
> > `src/gz openwrt_core https://mirrors.cloud.tencent.com/lede/snapshots/targets/ramips/mt7621/packages src/gz openwrt_base https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/base src/gz openwrt_freifunk https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/freifunk src/gz openwrt_luci https://mirrors.cloud.tencent.com/lede/releases/18.06.8/packages/mipsel_24kc/luci src/gz openwrt_packages https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/packages src/gz openwrt_routing https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/routing src/gz openwrt_telephony https://mirrors.cloud.tencent.com/lede/snapshots/packages/mipsel_24kc/telephony`
> 
> 直接在config里添加就行应该

已经测试，那只是客户端……

**Comment by Hyy2001X** [comment]
不能开机自启动试试设置corntab

**Comment by sirliu** [comment]
> 不能开机自启动试试设置corntab

OK，我试一试吧
