### ISSUE TITLE
是否可以添加京东签到，每天能领到几毛钱也不错啊。

### ISSUE THREAD

**Issue by musaart** [Hyy2001X/AutoBuild-Actions#38]
是否可以添加京东签到，每天能领到几毛钱也不错啊。

**Comment by sirliu** [comment]
自己在config里添加就行了插件名称并编译....定制的才是最适合自己的。

**Comment by Hyy2001X** [comment]
下载地址 https://github.com/Hyy2001X/AutoBuild-Actions-BETA
