### ISSUE TITLE
请问如果我需要更改路由IP此命令应该加在哪里？

### ISSUE THREAD

**Issue by ccc919** [Hyy2001X/AutoBuild-Actions#42]
# Modify default IP
sed -i 's/192.168.1.1/192.168.50.1/g' package/base-files/files/bin/config_generate

**Comment by Hyy2001X** [comment]
写在 Diy-Part1() {
里
sed -i 's/192.168.1.1/192.168.50.1/g' package/base-files/files/bin/config_generate

**Comment by Hyy2001X** [comment]
Diy-Part1 运行在克隆lede源码之后，更新FEEDS之前
Diy-Part2 运行在更新FEEDS之后，下载dl库之前
Diy-Part3 运行在固件编译成功之后

**Comment by ccc919** [comment]
感谢感谢

**Comment by ccc919** [comment]
关于定时更新是不是无法使用 ，我把注释去掉以后出错

**Comment by shyperwang** [comment]
@Hyy2001X 最新脚本已经删除 Diy-Part1() 了，修改ip的命令应该放在哪里？是不是放在Firmware-Diy_Base()的case ${Source_Owner}前？

**Comment by Hyy2001X** [comment]
> @Hyy2001X 最新脚本已经删除 Diy-Part1() 了，修改ip的命令应该放在哪里？是不是放在Firmware-Diy_Base()的case ${Source_Owner}前，还是放在Firmware-Diy()里面？

建议放在 Firmware-Diy() 里，我一般不回去改 AutoBuild_DiyScript.sh文件，方便同步我的最新改动
