### ISSUE TITLE
stable 版现在没有了嘛？  stable的20210113还能在线更新嘛？

### ISSUE THREAD

**Issue by iJayscn** [Hyy2001X/AutoBuild-Actions#48]
stable 版现在没有了嘛？  stable的20210113还能在线更新嘛？

**Comment by Hyy2001X** [comment]
已经取消更新通道,需要手动从Release下载稳定版,当前最新的稳定版本会在顶部标出

**Comment by iJayscn** [comment]
> 已经取消更新通道,需要手动从Release下载稳定版,当前最新的稳定版本会在顶部标出

请问手动下载，可以保留配置升级吗？

**Comment by Hyy2001X** [comment]
> > 已经取消更新通道,需要手动从Release下载稳定版,当前最新的稳定版本会在顶部标出
> 
> 请问手动下载，可以保留配置升级吗？

可以，web升级即可，不过隔了这么久的版本，建议不保留配置

**Comment by iJayscn** [comment]
> > > 已经取消更新通道,需要手动从Release下载稳定版,当前最新的稳定版本会在顶部标出
> > 
> > 
> > 请问手动下载，可以保留配置升级吗？
> 
> 可以，web升级即可，不过隔了这么久的版本，建议不保留配置

好的 谢谢
