### ISSUE TITLE
关于添加PassWall

### ISSUE THREAD

**Issue by NaiHeKK** [Hyy2001X/AutoBuild-Actions#49]
大佬，现在要添加**Passwall**：`ExtraPackages git other openwrt-passwall https://github.com/xiaorouji main`这个应该放在`Scripts/AutoBuild_DiyScript.sh`的Diy-Part2里还是`CustomPackages/d-team_newifi-d2`里面啊？

**Comment by Hyy2001X** [comment]
都可，专门添加一个CustomPackages是为了多设备的编译。
想添加到Diy-Part2里就写ExtraPackages git other openwrt-passwall https://github.com/xiaorouji main
想添加CustomPackages到里就写git other openwrt-passwall https://github.com/xiaorouji main

**Comment by Hyy2001X** [comment]
都可，专门添加一个CustomPackages是为了多设备的编译。
想添加到Diy-Part2里就写ExtraPackages git other openwrt-passwall https://github.com/xiaorouji main
想添加CustomPackages到里就写git other openwrt-passwall https://github.com/xiaorouji main

**Comment by NaiHeKK** [comment]
> 都可，专门添加一个CustomPackages是为了多设备的编译。
> 想添加到Diy-Part2里就写ExtraPackages git other openwrt-passwall https://github.com/xiaorouji main
> 想添加CustomPackages到里就写git other openwrt-passwall https://github.com/xiaorouji main

好的，谢谢大佬
