### ISSUE TITLE
newifi d2的固件luci-app-passwall不包含在选项内了吗？

### ISSUE THREAD

**Issue by shyperwang** [Hyy2001X/AutoBuild-Actions#50]
newifi d2的固件luci-app-passwall不包含在选项内了吗？好像没有这个选项了，单独安装难度有点难度，依赖比较多，建议编译的时候选择好，直接编译进去

**Comment by Hyy2001X** [comment]
手动添加 git other openwrt-passwall https://github.com/xiaorouji main 到 /CustomPackages/d-team_newifi-d2

**Comment by shyperwang** [comment]
> 手动添加 git other openwrt-passwall https://github.com/xiaorouji main 到 /CustomPackages/d-team_newifi-d2

命令添上去，没安装上，我再研究研究
