### ISSUE TITLE
关于风格包luci-theme-argon的适用区别

### ISSUE THREAD

**Issue by teasiu** [Hyy2001X/AutoBuild-Actions#54]
luci-theme-argon非常受欢迎，多数用户都采用这个界面定制。
以下测试过：
在Scripts/AutoBuild_Function.sh第92行
19.07） ExtraPackages git other luci-theme-argon https://github.com/jerrykuku v2.2.5
21.02） ExtraPackages git other luci-theme-argon https://github.com/jerrykuku master
如果19.07用了master，那么手机登录界面打不开子菜单。不要混用了。

**Comment by Hyy2001X** [comment]
已添加相应的开关
