### ISSUE TITLE
关于K2P的mtwifi

### ISSUE THREAD

**Issue by wwq133585** [Hyy2001X/AutoBuild-Actions#6]
是不是K2P的mtwifi要勾选比较好？

**Comment by Hyy2001X** [comment]
mtwifi即闭源驱动，k2p的配置文件是默认勾选luci-app-mtwifi的,建议勾选

**Comment by wwq133585** [comment]
升级时bash no found
反而curl可以，直接输入我自己的路径一键升级完成
看了下默认保留配置的，这样会出什么问题吗

**Comment by Hyy2001X** [comment]
> 升级时bash no found
> 反而curl可以，直接输入我自己的路径一键升级完成
> 看了下默认保留配置的，这样会出什么问题吗

不会
