### ISSUE TITLE
关于autoupdate -x自动更新

### ISSUE THREAD

**Issue by teasiu** [Hyy2001X/AutoBuild-Actions#60]
这个自动更新很棒。
但是有一个逻辑缺陷，
104行 Github_Raw="https://raw.githubusercontent.com/${Author}/master"
105行 CLOUD_Script="${Github_Raw}/Scripts/AutoUpdate.sh"
这个逻辑相当于fork的仓库除非自己修改AutoUpdate.sh，否则永远更新不到你的更新。
建议105行修改为：
CLOUD_Script="https://raw.githubusercontent.com/Hyy2001X/AutoBuild-Actions/master/Scripts/AutoUpdate.sh"

我相信作者编写这个更新脚本的目的就是为了帮助用户在使用autoupdate脚本时，不断优化下载体验。
所以，用户真正想用的，是作者的脚本。而不是自己修改的脚本。
但是为了个性化，就fork了作者的仓库来定制自己的固件，
所以，这个${Author}的逻辑就出现了差异了。

国内用户，可以用这个：
https://gh111.herokuapp.com/Hyy2001X/AutoBuild-Actions/raw/master/Scripts/AutoUpdate.sh
我作了一个国内用户使用github的全球转发，
详情请看https://github.com/slitaz-cn/heroku-github

**Comment by Hyy2001X** [comment]
AutoUpdate.sh地址已经修改指向为我的仓库并优化了一下镜像使用逻辑,考虑到存在即使翻墙也因为污染无法访问 raw.github 的问题,因此新增了一个参数 -px(-xp): 使用FastGit镜像更新 AutoUpdate.sh 脚本,最后感谢你的建议！
