### ISSUE TITLE
newifi3安装后，在线更新版本一次，目前版本是20210509，断电自动重启

### ISSUE THREAD

**Issue by wgd0813** [Hyy2001X/AutoBuild-Actions#62]
因为使用环境的原因，不得已偶尔要断一下电。
但是每次断电以后，再插电，就回到了刚安装的样子，所有的配置都没有了，就像恢复出厂了一样，
这种情况正常吗？

**Comment by Hyy2001X** [comment]
不正常 试试更新一下breed到最新版
