### ISSUE TITLE
同步“新路由3添加 DNSFilter”后编译失败

### ISSUE THREAD

**Issue by NaiHeKK** [Hyy2001X/AutoBuild-Actions#63]
具体错误如下：
run custom Firmware-Diy Scripts
.....
checking out package [luci-app-dnsfilter] to package/other
Error: Process completed with exit code 128
[详情](https://github.com/NaiHeKK/AutoBuild-Actions/runs/2580645947?check_suite_focus=true)

**Comment by Hyy2001X** [comment]
发现了，这个仓库主分支不是master，添加main就好了

**Comment by NaiHeKK** [comment]
> 发现了，这个仓库主分支不是master，添加main就好了

好滴，谢谢大佬
