### ISSUE TITLE
AutoBuild_Function.sh脚本运行错误

### ISSUE THREAD

**Issue by shyperwang** [Hyy2001X/AutoBuild-Actions#65]
如图，`sed -i "s/${Old_IP_Address}/${New_IP_Address}/g" package/base-files/files/bin/config_generate`后语句是做什么用的？我在自动action的时候，发现到这里会出现错误。将后面的六句注解掉就可以运行了。具体我不是太懂，熟悉语句的大佬可以观察一下。
![微信截图_20210518142720](https://user-images.githubusercontent.com/39717964/118606660-46069980-b7ea-11eb-9176-6b66e9502178.png)
![微信截图_20210518142835](https://user-images.githubusercontent.com/39717964/118606665-47d05d00-b7ea-11eb-9d35-0eb2c0390a39.png)

**Comment by Hyy2001X** [comment]
收到,感谢反馈

**Comment by Paris0-0** [comment]
同,我也是这里报错,要注销掉才能正常用吗
