### ISSUE TITLE
请教一下 编译newifi3v1.2（闪存32M 内存512M）19.07.7要改哪些地方？

### ISSUE THREAD

**Issue by Thanf-code** [Hyy2001X/AutoBuild-Actions#67]
编译 新路由3v1.2（闪存32M 内存512M）的openwrt19.07.7版  要改动哪些地方？

**Comment by Hyy2001X** [comment]
修改 yml 文件,REPO_URL 改为 https://github.com/openwrt/openwrt/
REPO_BRANCH 改为 v19.07.7
修改 Scripts/AutoBuild_DiyScript.sh 中的 INCLUDE_Obsolete_PKG_Compatible 为 true

**Comment by Thanf-code** [comment]
![image](https://user-images.githubusercontent.com/82493550/118925675-abd15d80-b971-11eb-90aa-01c7c039ce90.png)


> 先同步我的最新改动,然后
> 修改 yml 文件,REPO_URL 改为 https://github.com/openwrt/openwrt/
> REPO_BRANCH 改为 v19.07.7
> 修改 Scripts/AutoBuild_DiyScript.sh 中的 INCLUDE_Obsolete_PKG_Compatible 为 true

编译时出现如下错误， 编译完成后有影响吗？
![image](https://user-images.githubusercontent.com/82493550/118925788-dfac8300-b971-11eb-9239-2c2ab184cb67.png)

**Comment by Thanf-code** [comment]
> 先同步我的最新改动,然后
> 修改 yml 文件,REPO_URL 改为 https://github.com/openwrt/openwrt/
> REPO_BRANCH 改为 v19.07.7
> 修改 Scripts/AutoBuild_DiyScript.sh 中的 INCLUDE_Obsolete_PKG_Compatible 为 true

编译是出现如下错误，编译完成后有影响吗？
![image](https://user-images.githubusercontent.com/82493550/118925952-25694b80-b972-11eb-8fcf-45621c5fe576.png)

**Comment by Hyy2001X** [comment]
> > 先同步我的最新改动,然后
> > 修改 yml 文件,REPO_URL 改为 https://github.com/openwrt/openwrt/
> > REPO_BRANCH 改为 v19.07.7
> > 修改 Scripts/AutoBuild_DiyScript.sh 中的 INCLUDE_Obsolete_PKG_Compatible 为 true
> 
> 编译是出现如下错误，编译完成后有影响吗？
> ![image](https://user-images.githubusercontent.com/82493550/118925952-25694b80-b972-11eb-8fcf-45621c5fe576.png)

没有影响,无视即可

**Comment by Thanf-code** [comment]
> > > 先同步我的最新改动,然后
> > > 修改 yml 文件,REPO_URL 改为 https://github.com/openwrt/openwrt/
> > > REPO_BRANCH 改为 v19.07.7
> > > 修改 Scripts/AutoBuild_DiyScript.sh 中的 INCLUDE_Obsolete_PKG_Compatible 为 true
> > 
> > 
> > 编译是出现如下错误，编译完成后有影响吗？
> > ![image](https://user-images.githubusercontent.com/82493550/118925952-25694b80-b972-11eb-8fcf-45621c5fe576.png)
> 
> 没有影响,无视即可

无法ssh登录
![image](https://user-images.githubusercontent.com/82493550/118950300-a6354100-b98c-11eb-8b85-5b540041bbba.png)

**Comment by Thanf-code** [comment]
> > > > 先同步我的最新改动,然后
> > > > 修改 yml 文件,REPO_URL 改为 https://github.com/openwrt/openwrt/
> > > > REPO_BRANCH 改为 v19.07.7
> > > > 修改 Scripts/AutoBuild_DiyScript.sh 中的 INCLUDE_Obsolete_PKG_Compatible 为 true
> > > 
> > > 
> > > 编译是出现如下错误，编译完成后有影响吗？
> > > ![image](https://user-images.githubusercontent.com/82493550/118925952-25694b80-b972-11eb-8fcf-45621c5fe576.png)
> > 
> > 
> > 没有影响,无视即可
> 
> 无法ssh登录
> ![image](https://user-images.githubusercontent.com/82493550/118950300-a6354100-b98c-11eb-8b85-5b540041bbba.png)

可以登录 就是耗时有点长
