### ISSUE TITLE
samba插件是最新的吗？

### ISSUE THREAD

**Issue by whyjes** [Hyy2001X/AutoBuild-Actions#69]
samba插
![ED8D13B7-2B65-4E83-810F-95F5AC5CF094](https://user-images.githubusercontent.com/62455419/119082436-aedf5300-ba30-11eb-9f1b-f56fae60332e.png)
件是最新的吗？iPhone局域网共享文件只读，安卓可以读写

**Comment by Hyy2001X** [comment]
没有改过相关代码,相比原生openwrt不是最新的

**Comment by whyjes** [comment]
> 没有改过相关代码,相比原生openwrt不是最新的

谢谢，已经解决了，是硬盘格式不兼容iOS系统
