### ISSUE TITLE
网页界面的自动更新显示异常，无法获取到版本信息

### ISSUE THREAD

**Issue by Paris0-0** [Hyy2001X/AutoBuild-Actions#72]
如图，用命令行测试是可以获取到的
![IMG_1415](https://user-images.githubusercontent.com/11692160/120924658-3bfbfa80-c707-11eb-998b-d01388c4b275.png)

**Comment by Hyy2001X** [comment]
已更新整体架构,不适用于旧版固件,需要同步我的改动再进行编译

**Comment by Hyy2001X** [comment]
旧版固件请手动从Github下载更新

**Comment by Paris0-0** [comment]
我已经同步到自己的仓了,除了config和diy文件改了其他没动,今天刚编译的,不保留配置也是也这样,是要把release里的老版本删掉吗

**Comment by Paris0-0** [comment]
哦看到最新的了😂,之前还没有的,马上同步试试

**Comment by Hyy2001X** [comment]
看了下AutoUpdate脚本是v5.7.6的,最新是v6.0

**Comment by Paris0-0** [comment]
好的,之前一直是8天前的更新好像刚刚才有新的出来
