### ISSUE TITLE
luci界面无法更新,命令可以

### ISSUE THREAD

**Issue by Paris0-0** [Hyy2001X/AutoBuild-Actions#74]
日志显示:
Sun Jun 13 12:31:00 2021 daemon.err uhttpd[1888]: /bin/AutoUpdate.sh: line 400: /tmp/Downloads/AutoBuild-lede-d-team_newifi-d2-R21.6.1-20210613-7f469.bin: Permission denied
Sun Jun 13 12:31:51 2021 daemon.err uhttpd[1888]: /bin/AutoUpdate.sh: line 400: /tmp/Downloads/AutoBuild-lede-d-team_newifi-d2-R21.6.1-20210613-7f469.bin: Permission denied
Sun Jun 13 12:33:01 2021 daemon.err uhttpd[1888]: /bin/AutoUpdate.sh: line 400: /tmp/Downloads/AutoBuild-lede-d-team_newifi-d2-R21.6.1-20210613-7f469.bin: Permission denied
Sun Jun 13 12:34:07 2021 daemon.err uhttpd[1888]: /bin/AutoUpdate.sh: line 400: /tmp/Downloads/AutoBuild-lede-d-team_newifi-d2-R21.6.1-20210613-7f469.bin: Permission denied

是不是和我开了https有关?

**Comment by Hyy2001X** [comment]
先更新一下脚本吧 `autoupdate -x`, 跟https没有关系

**Comment by Paris0-0** [comment]
同步了源码重新编译了固件,luci界面直接空白了😂

**Comment by Hyy2001X** [comment]
> 同步了源码重新编译了固件,luci界面直接空白了😂

调整了一下UI,试试`cp -a /rom/etc/config/autoupdate /etc/config/ && uci commit autoupdate`

**Comment by Paris0-0** [comment]
ui显示出来了,我再试试编译一个看能不能更新
