### ISSUE TITLE
同步最新代码后编译失败

### ISSUE THREAD

**Issue by NaiHeKK** [Hyy2001X/AutoBuild-Actions#75]
错误如下：

- Run AutoBuild_DiyScript.sh 

- /home/runner/work/AutoBuild-Actions/AutoBuild-Actions/Scripts/AutoBuild_DiyScript.sh: line 20: Replace_File: command not found
- [详情](https://github.com/NaiHeKK/AutoBuild-Actions/runs/2857723134?check_suite_focus=true)
大佬，是不是有什么东西删了啊

**Comment by Hyy2001X** [comment]
AutoBuild_DiyScript.sh: line 20: `Replace_File` 改成 Copy,或者 AutoBuild_DiyScript.sh 这个文件也同步一下

**Comment by Hyy2001X** [comment]
记得不保留配置更新固件
