### ISSUE TITLE
大神，能帮忙写个判断吗？感谢！

### ISSUE THREAD

**Issue by 281677160** [Hyy2001X/AutoBuild-Actions#77]
我想弄个判断，不会写，也不知道能不能写，所以来问问大神
我想判断openwrt/bin/targets/*/* 这个文件里面有没有带sysupgrade.bin的固件
如果有我就把这个固件改成指定名字，改名字我会，用mv就可以了，但是百度半天没弄明白怎么写判断
固件名字千奇百怪的，把固件名字改成统一的就方便多了，不用写那么多判断什么机子什么固件名字

**Comment by Hyy2001X** [comment]
生成的固件的名字都是有统一的格式的，找到规律组合一下就好了

**Comment by 281677160** [comment]
感谢！我找到方法了，刚测试完，现在比较方便了，出了X86,K3已经知道的，另外写名字，其他的都让它匹配.bin后缀了，检测到sysupgrade.bin就全部改成一个格式的名字，这样就不用考虑名字的问题搞的CP不到固件了，如果又不是X86,K3的，又不是sysupgrade.bin这个格式名字的固件就再说了。
我的方法就是&nbsp;if [[ `ls bin/targets/*/* | grep -c "sysupgrade.bin"` -eq '1' ]]; then&nbsp; 测试了老久才弄出来的，哈哈，实在是不懂这些




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hyy2001X/AutoBuild-Actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月21日(星期一) 晚上8:42
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Hyy2001X/AutoBuild-Actions] 大神，能帮忙写个判断吗？感谢！ (#77)





 
生成的固件的名字都是有统一的格式的，找到规律组合一下就好了
