### ISSUE TITLE
请问大神，定时更新的Github_Tags文件可以用代理下载吗?

### ISSUE THREAD

**Issue by 281677160** [Hyy2001X/AutoBuild-Actions#81]
因为github筑墙了，不翻墙的话，第一步就过不去了，如果这个文件也可以用代理下载下来，然后检测就方便了，现在的情况下，不翻墙没办法用

在github下载文件的话，用 https://ghproxy.com 代理好像比你现在的这个好用，我用这个下载基本不会下载不了，用你现在的这个经常下载不了

**Comment by Hyy2001X** [comment]
API 地址应该不能代理

**Comment by 281677160** [comment]
> API 地址应该不能代理

感谢回复，那就难搞了，没翻墙，第一步就过不去了，唉

**Comment by Hyy2001X** [comment]
我这边的网络不翻墙也可以访问API地址的，代理加速效果因区域而异，我看看能不能吧 ghproxy 也加进去

**Comment by 281677160** [comment]
> 我这边的网络不翻墙也可以访问API地址的，代理加速效果因区域而异，我看看能不能吧 ghproxy 也加进去

那么神奇，好多人都说不翻墙不能进github了，我2条网络，电信的2个月还是3个月前就不可以了，移动的是2个月左右吧就不可以了访问github了
