### ISSUE TITLE
无法编译应用过滤插件

### ISSUE THREAD

**Issue by Thanf-code** [Hyy2001X/AutoBuild-Actions#82]
插件地址https://github.com/destan19/OpenAppFilter

**Comment by Thanf-code** [comment]
![应用过滤插件编译出错](https://user-images.githubusercontent.com/82493550/123496800-74368f00-d65c-11eb-9467-cf9aaba888a7.png)

**Comment by Hyy2001X** [comment]
Use `git other OpenAppFilter destan19`
