### ISSUE TITLE
大神！

### ISSUE THREAD

**Issue by 281677160** [Hyy2001X/AutoBuild-Actions#85]
我在抄你那个CPU温度重新获取文件，看了下你的文件，天灵的源码老早就没有lean文件了，他的在package/emortal里面

**Comment by Hyy2001X** [comment]
感谢提醒，已修改

**Comment by 281677160** [comment]
呵呵，客气了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hyy2001X/AutoBuild-Actions"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 晚上11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hyy2001X/AutoBuild-Actions] 大神！ (#85)





 
感谢提醒，已修改
