### ISSUE TITLE
关于 不支持所上传的映像文件格式，请选择适合当前平台的通用映像文件。

### ISSUE THREAD

**Issue by NaiHeKK** [Hyy2001X/AutoBuild-Actions#91]
这个似乎并不是内核的问题，我今天下午同步了你的更新之后重新编译了固件上传更新还是提示`不支持所上传的映像文件格式，请选择适合当前平台的通用映像文件。`

**Comment by NaiHeKK** [comment]
或者是内核没切回去？

**Comment by Hyy2001X** [comment]
内核是切换回去了,但是 lean 大适配 5.10 时固件更新这一部分的代码也做了改动,所以先用 `sysupgrade -F` 更新固件吧

**Comment by NaiHeKK** [comment]
试了下还是得breed刷
