### ISSUE TITLE
同步源码编译后在Run AutoBuild_DiyScript.sh出错

### ISSUE THREAD

**Issue by Paris0-0** [Hyy2001X/AutoBuild-Actions#92]
Run chmod +x Scripts/AutoBuild_*.sh
23
/home/runner/work/_temp/7de331de-802b-4670-8b81-2aa6b1fa7cf3.sh: line 7: Firmware-Diy_Base: command not found
24
Error: Process completed with exit code 127.

就同步了下源码,其他没改

**Comment by Hyy2001X** [comment]
[这个文件](https://github.com/Paris0-0/AutoBuild-Actions/blob/master/.github/workflows/Newifi%20D2.yml) 也需要同步一下改动 因为有些函数名称改过了 导致旧的 yml 调用不到

**Comment by Paris0-0** [comment]
好的
