### ISSUE TITLE
immortalwrt 18.06 主題套件衝突

### ISSUE THREAD

**Issue by kai456789** [Hyy2001X/AutoBuild-Actions#93]
https://github.com/immortalwrt/immortalwrt/tree/openwrt-18.06
用此源碼分支 編譯acrh17 .config沒變動
會出現luci-theme-argon與luci-theme-argonv3重複 編譯失敗

https://paste.ubuntu.com/p/Pwx68yQn55/

**Comment by Hyy2001X** [comment]
删除 仓库/Configs/Common 文件即可,这个文件里的内容会写到所有机型的 config 中

**Comment by kai456789** [comment]
刪除 倉庫/Configs/Common  成功編譯 感謝
