### ISSUE TITLE
可否适配K2这个老机器

### ISSUE THREAD

**Issue by laomao9000** [Hyy2001X/AutoBuild-Actions#97]
非常感谢！目前在用newifi3的固件，效果很棒！
K2有几台在做小房间中继，运行的系统很老了，想更新下，希望能做适配！
谢谢！

**Comment by 281677160** [comment]
新系统兼容未必好的

**Comment by Hyy2001X** [comment]
> 非常感谢！目前在用newifi3的固件，效果很棒！
> K2有几台在做小房间中继，运行的系统很老了，想更新下，希望能做适配！
> 谢谢！

我没有 K2，也没有他的信息，所以编译出来也只能你们自己测试
