### ISSUE TITLE
同步源码后编译错误

### ISSUE THREAD

**Issue by Paris0-0** [Hyy2001X/AutoBuild-Actions#98]
在compile步骤提示This step has been truncated due to its large size. Download the full logs from the  menu once the workflow run has completed.

**Comment by Paris0-0** [comment]
忘了同步 workflows.了

**Comment by Paris0-0** [comment]
同步了yml还是一样的报错

**Comment by NaiHeKK** [comment]
你已经编译完成了啊

**Comment by Paris0-0** [comment]
删了几个ssrp的选项今早完成了,昨天的三个全报错..不知道为啥

**Comment by NaiHeKK** [comment]
> 删了几个ssrp的选项今早完成了,昨天的三个全报错..不知道为啥

你是不是自己加了插件

**Comment by NaiHeKK** [comment]
> 删了几个ssrp的选项今早完成了,昨天的三个全报错..不知道为啥

感觉vssr也没passwall好用啊，我之前一个固件vssr openclash ssrp passwall然后感觉还是passwall好用点

**Comment by Paris0-0** [comment]
passwall看上去有点复杂还没用,vssr只是装着也没用,现在还是用ssrp了,有时间研究研究passwall

**Comment by NaiHeKK** [comment]
> passwall看上去有点复杂还没用,vssr只是装着也没用,现在还是用ssrp了,有时间研究研究passwall

哦哦，上面那个错误看起来就是你插件加太多了，大小超过限制。当然只是猜测。还有你似乎add了两个maxminddb
