### ISSUE TITLE
new wifi 3 重启后 adh 无法使用

### ISSUE THREAD

**Issue by izhengchengjin** [Hyy2001X/AutoBuild-Actions#99]
RT 重启后，adh 无法使用。并且 DNS 设置中 dns 转发功能的配置被自动重置。

**Comment by Hyy2001X** [comment]
可否给出相关的配置呢，例如设置界面截图或者log

**Comment by izhengchengjin** [comment]
由于已经更换其他固件了，日志截图都无了。
当时的配置是在 dns 转发添加了一条 clash 的 127.0.0.1#7874
adh 正常配置。
adh 作为 clash 的上游 dns ，端口设置为5550.
重启后 adh 无法下载核心，导致无法启动。

**Comment by Hyy2001X** [comment]
> 当时的配置是在 dns 转发添加了一条 clash 的 127.0.0.1#7874

重启后/tmp下的adg核心丢失，这样一来会导致你clash现有的dns出错导致不能翻墙，不翻墙就不能下载核心

**Comment by izhengchengjin** [comment]
> > 当时的配置是在 dns 转发添加了一条 clash 的 127.0.0.1#7874
> 
> 重启后/tmp下的adg核心丢失，这样一来会导致你clash现有的dns出错导致不能翻墙，不翻墙就不能下载核心
